version: '3.8'

services:
  ml-service:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models  # For DVC model files
      - ./data:/app/data      # For DVC data files
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
