version: '3.8'

services:
  ml-service:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/app/models  # For DVC model files
      - ./data:/app/data      # For DVC data files
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: ml-service-redis
    command: >
      redis-server --appendonly yes --maxmemory-policy volatile-ttl
    ports:
      - "6379:6379"
    restart: unless-stopped
